### Login Client
POST http://localhost:4040/api/v1/auth/login
Content-Type: application/json

{
  "email": "javlonpa1n@gmail.com",
  "password": "qwerty123"
}

### Login Admin
POST http://localhost:4040/api/v1/auth/login
Content-Type: application/json

{
  "email": "abdurakhmanovjb@icloud.com",
  "password": "Javlondev"
}

### Registration
POST http://localhost:4040/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Java",
  "surname": "Abdu",
  "email": "javlonpa1n@gmail.com",
  "password": "qwerty123"
}

### Verification
GET http://localhost:4040/api/v1/auth/verification/eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXZsb25wYTFuQGdtYWlsLmNvbSIsImlhdCI6MTY1NDc2NTUzOCwiZXhwIjoxNjU0NzY1NzE4LCJwcm9maWxlSWQiOiIyYzlhNjA4MTgxNDdiNTJjMDE4MTQ3YjY0ZTA0MDAwMSIsImlzcyI6IldlYXRoZXIgUHJvZHVjdGlvbiJ9.NuoU_6WNsF6G2ugcYZHb9-T_LLQExpxSJc76FaWK3cc

