### Login Client
POST http://localhost:4040/api/v1/auth/login
Content-Type: application/json

{
  "email": "abs@gmail.com",
  "password": "qwerty123"
}

### Login Admin
POST http://localhost:4040/api/v1/auth/login
Content-Type: application/json

{
  "email": "abdurakhmanovjb@icloud.com",
  "password": "Javlondev"
}

### Registration
POST http://localhost:4040/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Java",
  "surname": "1.8",
  "email": "abs@gmail.com",
  "password": "qwerty123"
}

### Verification
GET http://localhost:4040/api/v1/auth/verification/eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYnNAZ21haWwuY29tIiwiaWF0IjoxNjU0Njk4MjgzLCJleHAiOjE2NTQ2OTg0NjMsInByb2ZpbGVJZCI6IjJjOWE2MDgxODE0M2IzNzEwMTgxNDNiNDExOTYwMDAwIiwiaXNzIjoiV2VhdGhlciBQcm9kdWN0aW9uIn0.GES5T4xUT9N-a2khYzcHsQ7jycG7Llt_STD1-WqF4AU
