### Profile Info - CLIENT
GET http://localhost:4040/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXZsb25wYTFuQGdtYWlsLmNvbSIsImlhdCI6MTY1NDY5Nzg1OSwiZXhwIjoxNjU1MzAyNjU5LCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.4-VXdtx1RchyYYX1TMrzqaXtSvnUNewd3yrIacuQ6eU
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmR1cmFraG1hbm92amJAaWNsb3VkLmNvbSIsImlhdCI6MTY1NDY5Nzk1MCwiZXhwIjoxNjU1MzAyNzUwLCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.vDimNdjMjI0QMKq_t_VqavIe8W1FiATEuiz-CFJy7Mg

### Update Profile Bio - CLIENT
PUT http://localhost:4040/api/v1/profile/bio
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXZsb25wYTFuQGdtYWlsLmNvbSIsImlhdCI6MTY1NDY5Nzg1OSwiZXhwIjoxNjU1MzAyNjU5LCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.4-VXdtx1RchyYYX1TMrzqaXtSvnUNewd3yrIacuQ6eU
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmR1cmFraG1hbm92amJAaWNsb3VkLmNvbSIsImlhdCI6MTY1NDY5Nzk1MCwiZXhwIjoxNjU1MzAyNzUwLCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.vDimNdjMjI0QMKq_t_VqavIe8W1FiATEuiz-CFJy7Mg

{
  "name": "Javlon",
  "surname": "Abdu"
}

### Update Profile Email - ANY
PUT http://localhost:4040/api/v1/profile/email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXZsb25wYTFuQGdtYWlsLmNvbSIsImlhdCI6MTY1NDY5Nzg1OSwiZXhwIjoxNjU1MzAyNjU5LCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.4-VXdtx1RchyYYX1TMrzqaXtSvnUNewd3yrIacuQ6eU
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmR1cmFraG1hbm92amJAaWNsb3VkLmNvbSIsImlhdCI6MTY1NDY5Nzk1MCwiZXhwIjoxNjU1MzAyNzUwLCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.vDimNdjMjI0QMKq_t_VqavIe8W1FiATEuiz-CFJy7Mg

{
  "email": "abs123@gmail.com"
}

### Put Profile Email - ANY
GET http://localhost:4040/api/v1/profile/eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYnMxMjNAZ21haWwuY29tIiwiaWF0IjoxNjU0NzA4ODU1LCJleHAiOjE2NTQ3MDkwMzUsInByb2ZpbGVJZCI6IjJjOWE2MDgxODEzZDg4NDUwMTgxM2Q4ODRlOGEwMDAwIiwiaXNzIjoiV2VhdGhlciBQcm9kdWN0aW9uIn0.DyN4Nz5seu5CzgKgebhyCtcsntm-6ydqhdnlU8km-V8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXZsb25wYTFuQGdtYWlsLmNvbSIsImlhdCI6MTY1NDY5Nzg1OSwiZXhwIjoxNjU1MzAyNjU5LCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.4-VXdtx1RchyYYX1TMrzqaXtSvnUNewd3yrIacuQ6eU
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmR1cmFraG1hbm92amJAaWNsb3VkLmNvbSIsImlhdCI6MTY1NDY5Nzk1MCwiZXhwIjoxNjU1MzAyNzUwLCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.vDimNdjMjI0QMKq_t_VqavIe8W1FiATEuiz-CFJy7Mg

### Update Profile Password - ANY
PUT http://localhost:4040/api/v1/profile/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXZsb25wYTFuQGdtYWlsLmNvbSIsImlhdCI6MTY1NDY5Nzg1OSwiZXhwIjoxNjU1MzAyNjU5LCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.4-VXdtx1RchyYYX1TMrzqaXtSvnUNewd3yrIacuQ6eU
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmR1cmFraG1hbm92amJAaWNsb3VkLmNvbSIsImlhdCI6MTY1NDY5Nzk1MCwiZXhwIjoxNjU1MzAyNzUwLCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.vDimNdjMjI0QMKq_t_VqavIe8W1FiATEuiz-CFJy7Mg

{
  "oldPassword": "qwerty123",
  "password": "Javlondev"
}

### Delete Profile - CLIENT
DELETE http://localhost:4040/api/v1/profile/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYnNAZ21haWwuY29tIiwiaWF0IjoxNjU0NzA5MzczLCJleHAiOjE2NTUzMTQxNzMsImlzcyI6IldlYXRoZXIgUHJvZHVjdGlvbiJ9.0GM2gzBrxX3PGtdasAdq8Wt2BHC8SCwZt8DgyyyBiuI

### Update Profile Role - ADMIN
PUT http://localhost:4040/api/v1/profile/role/2c9a60818144589701814458a14d0000
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXZsb25wYTFuQGdtYWlsLmNvbSIsImlhdCI6MTY1NDY5Nzg1OSwiZXhwIjoxNjU1MzAyNjU5LCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.4-VXdtx1RchyYYX1TMrzqaXtSvnUNewd3yrIacuQ6eU
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmR1cmFraG1hbm92amJAaWNsb3VkLmNvbSIsImlhdCI6MTY1NDY5Nzk1MCwiZXhwIjoxNjU1MzAyNzUwLCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.vDimNdjMjI0QMKq_t_VqavIe8W1FiATEuiz-CFJy7Mg

### Update Profile Status - ADMIN
PUT http://localhost:4040/api/v1/profile/status/2c9a60818144589701814458a14d0000
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXZsb25wYTFuQGdtYWlsLmNvbSIsImlhdCI6MTY1NDY5Nzg1OSwiZXhwIjoxNjU1MzAyNjU5LCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.4-VXdtx1RchyYYX1TMrzqaXtSvnUNewd3yrIacuQ6eU
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmR1cmFraG1hbm92amJAaWNsb3VkLmNvbSIsImlhdCI6MTY1NDY5Nzk1MCwiZXhwIjoxNjU1MzAyNzUwLCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.vDimNdjMjI0QMKq_t_VqavIe8W1FiATEuiz-CFJy7Mg

### Delete Profile - ADMIN
DELETE http://localhost:4040/api/v1/profile/delete/2c9a60818144589701814458a14d0000
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXZsb25wYTFuQGdtYWlsLmNvbSIsImlhdCI6MTY1NDY5Nzg1OSwiZXhwIjoxNjU1MzAyNjU5LCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.4-VXdtx1RchyYYX1TMrzqaXtSvnUNewd3yrIacuQ6eU
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmR1cmFraG1hbm92amJAaWNsb3VkLmNvbSIsImlhdCI6MTY1NDY5Nzk1MCwiZXhwIjoxNjU1MzAyNzUwLCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.vDimNdjMjI0QMKq_t_VqavIe8W1FiATEuiz-CFJy7Mg

### Profile List - ADMIN
GET http://localhost:4040/api/v1/profile/list
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXZsb25wYTFuQGdtYWlsLmNvbSIsImlhdCI6MTY1NDY5Nzg1OSwiZXhwIjoxNjU1MzAyNjU5LCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.4-VXdtx1RchyYYX1TMrzqaXtSvnUNewd3yrIacuQ6eU
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmR1cmFraG1hbm92amJAaWNsb3VkLmNvbSIsImlhdCI6MTY1NDY5Nzk1MCwiZXhwIjoxNjU1MzAyNzUwLCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.vDimNdjMjI0QMKq_t_VqavIe8W1FiATEuiz-CFJy7Mg

{
  "name": "Ja",
  "surname": "A",
  "email": "j",
  "role": "ROLE_CLIENT",
  "status": "ACTIVE",
  "deletedDate": true,
  "createdDate": true
}

### Profile Pagination - ADMIN
GET http://localhost:4040/api/v1/profile/page?page=0&size=15
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXZsb25wYTFuQGdtYWlsLmNvbSIsImlhdCI6MTY1NDY5Nzg1OSwiZXhwIjoxNjU1MzAyNjU5LCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.4-VXdtx1RchyYYX1TMrzqaXtSvnUNewd3yrIacuQ6eU
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmR1cmFraG1hbm92amJAaWNsb3VkLmNvbSIsImlhdCI6MTY1NDY5Nzk1MCwiZXhwIjoxNjU1MzAyNzUwLCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.vDimNdjMjI0QMKq_t_VqavIe8W1FiATEuiz-CFJy7Mg
