### Get Current Weather
GET http://localhost:4040/api/v1/weather?location=Samarkand
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXZsb25wYTFuQGdtYWlsLmNvbSIsImlhdCI6MTY1NDY5Nzg1OSwiZXhwIjoxNjU1MzAyNjU5LCJpc3MiOiJXZWF0aGVyIFByb2R1Y3Rpb24ifQ.4-VXdtx1RchyYYX1TMrzqaXtSvnUNewd3yrIacuQ6eU
